power <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
power.sub <- subset(power, Date=="1/2/2007" | Date=="2/2/2007")
power.sub$Global_active_power <- as.numeric(power.sub$Global_active_power)
hist(power.sub$Global_active_power, main="Global Active Power", xlab ="Global Active Power (kilowatts)", ylab="Frequency", col="red")
dev.copy(png, file="Plot1.png", width=480, height=480)
dev.off()
